name: Skywars
version: 4.2
author: UnioDex
main: me.uniodex.skywars.Skywars
depend: [ProtocolLib, FastAsyncWorldEdit]
softdepend: [Vault]
commands:
  skywars:
    description: Ana skywars komutları
    aliases: [sw]
  stats:
    description: İstatistikler
    aliases: [istatistikler]
  yenioyunagir:
    description: Yeni oyuna gir
  hub:
    description: Lobiye dön
    aliases: [lobi,lobby]
  kurallar:
    description: Kurallar
    aliases: [rules]
  vip:
    description: VIP bilgi gör
    aliases: [vipbilgi]
  help:
    description: Yardım
    aliases: [komutlar]
  coin:
    description: uCoin
    aliases: [ucoin]